import "@/shared/styles/global.css";
import { inter } from "@/shared/constants";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home Page - CloudHub",
  description: "Generated by create next app",
};

type TRootLayout = { children: Readonly<React.ReactNode> }

export default function RootLayout({ children }: TRootLayout) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>{children}</body>
    </html>
  );
}
